/* eslint-disable prettier/prettier */
const mdata = [
  {
    text: 'Match Mania 20%Off',
    lines: ['Enjoy ICC CWC23 matches with KFC'],
    image: require('../assets/match.png'),
    backgroundColor: '#af18f0',
  },
  {
    text: 'LEO Coffee',
    lines: [
      'Its time to have a coffee date flat 10% off at Leo Cafe',
    ],
    image: require('../assets/leo.png'),
    backgroundColor: '#e8153c',

  },
  {
    text: 'Kaithi Briyani',
    lines: ['Gear up fellow prisoners its time to meet Dilli for a feast'],
    image: require('../assets/briyani.png'),
    backgroundColor: '#6cbfd4',
  },
  {
    text: 'Navaratri Cravings',
    lines: ['Mouth watering delights from Saravana Bhavan for this Dusshera'],
    image: require('../assets/idli.png'),
    backgroundColor: '#ed1874',
  },
];

const scrolldata = [
  {
    image: require('../assets/beverages.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Beverages',
  },
  {
    image: require('../assets/sweets.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Sweets',
  },
  {
    image: require('../assets/vada.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Hot Snacks',
  },
  {
    image: require('../assets/dessert.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Desserts',
  },
  {
    image: require('../assets/chick.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Chicken',
  },
  {
    image: require('../assets/briyanipn.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Briyani',
  },
  {
    image: require('../assets/match.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Appetizers',
  },
  {
    image: require('../assets/kimchi.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Korean',
  },
  {
    image: require('../assets/dosa.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Indian',
  },
  {
    image: require('../assets/chinese.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Chinese',
  },
  {
    image: require('../assets/fish.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Fish',
  },
  {
    image: require('../assets/pizza.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Pizza',
  },

];

const restaurantData = [
  {
    imageSource: require('../assets/offer.png'),
    offerPrice: 'Offer Price 1',
    name: 'Hotel Name 1',
    rating: 'Rating: 4.5',
    description: 'Descriptive text about the hotel 1.',
  },
  {
    imageSource: require('../assets/offer.png'),
    offerPrice: 'Offer Price 2',
    name: 'Hotel Name 2',
    rating: 'Rating: 4.0',
    description: 'Descriptive text about the hotel 2.',
  },
  // Add more items as needed
];

const itemsData = [
  [
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
  ],
  [
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'cafine',
    },
  ],
  [
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'choco',
    },
  ],
];

const trustedData = [
  {
    source: require('../assets/coffel.jpg'),
    offerPrice: '$50',
    hotelName: 'Leo Coffee',
    ratings: '5/5',
    min: '24.3 mins',
    type: 'Coffee',
  },
  {
    source: require('../assets/sushi.jpg'),
    offerPrice: '$130',
    hotelName: 'Korean Aegyo',
    ratings: '4.7/5',
    min: '24.3 mins',
    type: 'Coffee',
  },
  {
    source: require('../assets/saravan.png'),
    offerPrice: '$20',
    hotelName: 'Hotel Saravana Bhavan',
    ratings: '4.3/5',
    min: '24.3 mins',
    type: 'Coffee',
  },
];
export {mdata, scrolldata, restaurantData, itemsData, trustedData};
