/* eslint-disable prettier/prettier */
const mdata = [
  {
    text: 'Match Mania 20%Off',
    lines: ['Enjoy ICC CWC23 matches with KFC'],
    image: require('../assets/burgerC.jpg'),
    backgroundColor: '#af18f0',
  },
  {
    text: 'LEO Coffee',
    lines: [
      'Its time to have a coffee date flat 10% off at Leo Cafe',
    ],
    image: require('../assets/bri.jpg'),
    backgroundColor: '#e8153c',

  },
  {
    text: 'Kaithi Briyani',
    lines: ['Gear up fellow prisoners its time to meet Dilli for a feast'],
    image: require('../assets/car2.png'),
    backgroundColor: '#6cbfd4',
  },
  {
    text: 'Navaratri Cravings',
    lines: ['Mouth watering delights from Saravana Bhavan for this Dusshera'],
    image: require('../assets/car4.png'),
    backgroundColor: '#ed1874',
  },
];

const scrolldata = [
  {
    image: require('../assets/beverages.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Beverages',
  },
  {
    image: require('../assets/sweets.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Sweets',
  },
  {
    image: require('../assets/vada.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Hot Snacks',
  },
  {
    image: require('../assets/dessert.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Desserts',
  },
  {
    image: require('../assets/chick.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Chicken',
  },
  {
    image: require('../assets/briyanipn.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Briyani',
  },
  {
    image: require('../assets/match.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Appetizers',
  },
  {
    image: require('../assets/kimchi.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Korean',
  },
  {
    image: require('../assets/dosa.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Indian',
  },
  {
    image: require('../assets/chinese.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Chinese',
  },
  {
    image: require('../assets/fish.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Fish',
  },
  {
    image: require('../assets/pizza.png'),
    width: 100,
    height: 100,
    marginRight: 60,
    name: 'Pizza',
  },

];

const restaurantData = [
  {
    imageSource: require('../assets/sweets.png'),
    offerPrice: 'from \u20B9 200',
    name: 'Kailash Parbhat',
    rating: '4.5',
    description: 'Sweets',
    place: 'ECR',
    texta: '10% OFF',
    textb: 'UPTO',
    min: '23 mins',
  },
  {
    imageSource: require('../assets/saravan.png'),
    offerPrice: '$20',
    name: 'Hotel Saravana Bhavan',
    rating: '4.0',
    description: ' hotel 2.',
    texta: 'hi',
    min: '23 mins',
    place: 'ECR',

  },
  {
    imageSource: require('../assets/sushi.jpg'),
    offerPrice: '$30',
    name: 'Hotel Name 1',
    rating: '4.5',
    description: 'hotel 1.',
    texta: 'hi',
    min: '23 mins',
    place: 'ECR',
  },
  {
    imageSource: require('../assets/offer.png'),
    offerPrice: '$20',
    name: 'Hotel Name 2',
    rating: '4.0',
    description: 'Descriptive text about the hotel 2.',
    texta: 'hi',
    min: '23 mins',
    place: 'ECR',
  },
  {
    imageSource: require('../assets/offer.png'),
    offerPrice: '$30',
    name: 'Hotel Name 1',
    rating: '4.5',
    description: 'Descriptive text about the hotel 1.',
    texta: 'hi',
    min: '23 mins',
    place: 'ECR',
  },
  {
    imageSource: require('../assets/offer.png'),
    offerPrice: '$20',
    name: 'Hotel Name 2',
    rating: '4.0',
    description: 'Descriptive text about the hotel 2.',
    texta: 'hi',
    min: '23 mins',
    place: 'ECR',
  },
  // Add more items as needed
];

const itemsData = [
  [
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: 'Upto \u20B9500',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '30% OFF',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Food - Seoul',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '20% OFF',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Food - Madrasi',
    },
    {
      source: require('../assets/pizza.png'),
      offerPrice: '\u20B950 Plus',
      hotelName: 'Pizzahut',
      ratings: '4.1/5',
      min: '24.3 mins',
      type: 'Pizza',
    },
    {
      source: require('../assets/briyanipn.png'),
      offerPrice: '\u20B9199 Only',
      hotelName: 'Thalappakatti Briyani',
      ratings: '4.6/5',
      min: '24.3 mins',
      type: 'Briyani',
    },
    {
      source: require('../assets/noodle.png'),
      offerPrice: '60% OFF',
      hotelName: 'Vikram Fast Foods',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Fast Food',
    },
  ],
  [
    {
      source: require('../assets/vada.png'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/coffee.png'),
      offerPrice: '\u20B920 Only',
      hotelName: 'Dilli Cafe',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/beverages.png'),
      offerPrice: '\u20B999 above',
      hotelName: 'Das & CO',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sweets.png'),
      offerPrice: '$20 off',
      hotelName: 'Lakshmi Sweets',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'cafine',
    },
  ],
  [
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/vada.png'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/coffel.jpg'),
      offerPrice: '$50',
      hotelName: 'Leo Coffee',
      ratings: '5/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/sushi.jpg'),
      offerPrice: '$130',
      hotelName: 'Korean Aegyo',
      ratings: '4.7/5',
      min: '24.3 mins',
      type: 'Coffee',
    },
    {
      source: require('../assets/saravan.png'),
      offerPrice: '$20',
      hotelName: 'Hotel Saravana Bhavan',
      ratings: '4.3/5',
      min: '24.3 mins',
      type: 'choco',
    },
  ],
];

const trustedData = [
  {
    source: require('../assets/coffel.jpg'),
    offerPrice: '$50',
    hotelName: 'Leo Coffee',
    ratings: '5/5',
    min: '24.3 mins',
    type: 'Coffee',
  },
  {
    source: require('../assets/sushi.jpg'),
    offerPrice: '$130',
    hotelName: 'Korean Aegyo',
    ratings: '4.7/5',
    min: '24.3 mins',
    type: 'Food - Seoul',
  },
  {
    source: require('../assets/saravan.png'),
    offerPrice: '$20',
    hotelName: 'Hotel Saravana Bhavan',
    ratings: '4.3/5',
    min: '24.3 mins',
    type: 'Food - Madrasi',
  },
];

const menuData = [
  {
    imageSource: require('../assets/choco.jpg'),
    offerPrice: 'from \u20B9 200',
    name: 'Chocolate Coffee',
    rating: '4.5 (67)',
    price: '\u20B9 170',
    description: 'Those woofers Im shit scared of that Bad Trip Im shit scared of that Those Chills Im shit scared ',
    place: 'ECR',
    texta: '10% OFF',
    textb: 'UPTO',
  },
  {
    imageSource: require('../assets/iceam.jpg'),
    offerPrice: 'from \u20B9 200',
    name: 'Iced Americano',
    rating: '4.5 (67)',
    price: '\u20B9 200',
    description: 'Those woofers Im shit scared of that Bad Trip Im shit scared of that Those Chills Im shit scared ',
    place: 'ECR',
    texta: '10% OFF',
    textb: 'UPTO',

  },
  {
    imageSource: require('../assets/mocha.jpg'),
    offerPrice: 'from \u20B9 200',
    name: 'Mocha',
    rating: '4.5 (67)',
    price: '\u20B9 229',
    description: 'Those woofers Im shit scared of that Bad Trip Im shit scared of that Those Chills Im shit scared ',
    place: 'ECR',
    texta: '10% OFF',
    textb: 'UPTO',
  },
  {
    imageSource: require('../assets/sweets.png'),
    offerPrice: 'from \u20B9 200',
    name: 'Chocolate Coffee',
    rating: '4.5 (67)',
    price: '\u20B9 170',
    description: 'Sweets',
    place: 'ECR',
    texta: '10% OFF',
    textb: 'UPTO',
  },
  {
    imageSource: require('../assets/sweets.png'),
    offerPrice: 'from \u20B9 200',
    name: 'Chocolate Coffee',
    rating: '4.5 (67)',
    price: '\u20B9 170',
    description: 'Sweets',
    place: 'ECR',
    texta: '10% OFF',
    textb: 'UPTO',
  },
  {
    imageSource: require('../assets/sweets.png'),
  offerPrice: 'from \u20B9 200',
  name: 'Chocolate Coffee',
  rating: '4.5 (67)',
  price: '\u20B9 170',
  description: 'Sweets',
  place: 'ECR',
  texta: '10% OFF',
  textb: 'UPTO',
  },
  // Add more items as needed
];

export {mdata, scrolldata, restaurantData, itemsData, trustedData, menuData};
